package com.gp.common;

public enum Operations {
	
	/** security operation */
	AUTHENTICATE,
	CHANGE_ACCOUNT_STATE,
	NEW_ACCOUNT,
	UPDATE_ACCOUNT,
	FIND_ACCOUNT,
	FIND_ACCOUNTS,
	REMOVE_ACCOUNT,
	CHANGE_PWD,
	EXIST_ACCOUNT,
	/** workgroup operation */
	NEW_WORKGROUP,
	UPDATE_WORKGROUP,
	FIND_WORKGROUP,
	FIND_WORKGROUPS,
	ADD_WORKGROUP_USER,
	REMOVE_WORKGROUP_USER,
	FIND_WORKGROUP_USERS,
	REMOVE_WORKGROUP,
	CLOSE_WORKGROUP,
	/** instance operation */
	FIND_INSTANCE,
	NEW_EXT_INSTANCE,
	UPDATE_INSTANCE,
	FIND_INSTANCES,
	/** system options */
	FIND_SYSOPTIONS,
	UPDATE_SYSOPTION,
	FIND_SYSOPT_GRPS,
	/** storage */
	FIND_STORAGES,
	NEW_STORAGE,
	UPDATE_STORAGE,
	REMOVE_STORAGE,
	FIND_STORAGE,
	/** cabinet */
	FIND_CABINETS,
	FIND_CABINET,
	NEW_CABINET,
	UPDATE_CABINET,
	REMOVE_CABINET,
	/** organization */
	FIND_ORGHIERS,
	FIND_ORGHIER,
	NEW_ORGHIER,
	UPDATE_ORGHIER,
	REMOVE_ORGHIER,
	ADD_ORGHIER_MEMBER,
	REMOVE_ORGHIER_MEMBER,
	FIND_ORGHIER_MEMBER,
	/** group */
	NEW_GROUP,
	UPDATE_GROUP,
	REMOVE_GROUP,
	FIND_GROUP,
	FIND_GROUPS,
	FIND_GROUP_USERS,
	ADD_GROUP_USER,
	REMOVE_GROUP_USER,
	/** folder */
	NEW_FOLDER,
	UPDATE_FOLDER,
	REMOVE_FOLDER,
	FIND_FOLDER,
	FIND_FOLDERS,
	/** file */
	NEW_FILE,
	UPDATE_FILE,
	REMOVE_FILE,
	FIND_FILE,
	FIND_FILES,
	/** image */
	NEW_IMAGE,
	UPDATE_IMAGE,
	REMOVE_IMAGE,
	FIND_IMAGE,
	FIND_IMAGES,
	UPDATE_DICT,
	FIND_DICTS,
	/** binary */
	FETCH_BIN_CHUNK,
	FETCH_BIN,
	STORE_BIN_CHUNK,
	STORE_BIN,
}
